name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Lint
        run: bun run lint

  test:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Tests
        run: bun run test

  test-browsers:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Install Playwright
        working-directory: playgrounds/ipfs-web3
        run: bunx playwright install --with-deps
      
      - name: Test e2e
        working-directory: playgrounds/ipfs-web3
        run: npm run test:e2e
        