name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Lint
        run: bun run lint

  test:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Tests
        run: bun run test

  test-browsers:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Install Playwright
        run: bunx playwright install --with-deps
      
      - name: Test e2e
        working-directory: playgrounds/ipfs-web3
        run: bun run test:e2e
    
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playgrounds/ipfs-web3/playwright-report/
          retention-days: 30